const ERROR_CODES = {
  GENERAL: {
    GENERIC_SERVER_ERROR: 'GENERIC_SERVER_ERROR',
  },
  USER: {
    FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
    DELETE_USER_ERROR: 'DELETE_USER_ERROR',
    UPDATE_USER_ROLE_ERROR: 'UPDATE_USER_ROLE_ERROR',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
  },
  VALIDATION: {
    INVALID_USER_ROLE: 'INVALID_USER_ROLE',
    INPUT_VALIDATION_ERROR: 'INPUT_VALIDATION_ERROR', // express-validator
    DUPLICATE_FIELD_VALUE: 'DUPLICATE_FIELD_VALUE',
    INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    MISSING_FIELDS: 'MISSING_FIELDS', // express-validator
  },
  AUTH: {
    JWT_INVALID: 'JWT_INVALID',
    JWT_EXPIRED: 'JWT_EXPIRED',
    NOT_LOGGED_IN: 'NOT_LOGGED_IN',
    INVALID_OR_EXPIRED_JWT: 'INVALID_OR_EXPIRED_JWT',
    USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
    PASSWORD_CHANGED_AFTER_TOKEN: 'AUTH_PASSWORD_CHANGED_AFTER_TOKEN',
  },
  ROUTES: {
    ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  },
};

module.exports = { ERROR_CODES };
