const ERROR_CODES = {
  // General
  GENERIC_SERVER_ERROR: 'GENERIC_SERVER_ERROR',

  // User
  FETCH_USERS_ERROR: 'FETCH_USERS_ERROR',
  DELETE_USER_ERROR: 'DELETE_USER_ERROR',
  UPDATE_USER_ROLE_ERROR: 'UPDATE_USER_ROLE_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',

  // Validation
  INVALID_USER_ROLE: 'INVALID_USER_ROLE',
  MONGOOSE_VALIDATION_ERROR: 'MONGOOSE_VALIDATION_ERROR',
  DUPLICATE_FIELD_VALUE: 'DUPLICATE_FIELD_VALUE',
  INVALID_ID_FORMAT: 'INVALID_ID_FORMAT',

  // Auth
  JWT_INVALID: 'JWT_INVALID',
  JWT_EXPIRED: 'JWT_EXPIRED',

  // Routes
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
};

module.exports = { ERROR_CODES };
